jobs:

  _cider-ci_include:

    # Minary Attack service tests
    - tests/cider-ci/jobs/minary.yml

    # Http reverse proxy tasks
    - tests/cider-ci/jobs/httpreverseproxy.yml

    # Http reverse proxy inject tasks
    - tests/cider-ci/jobs/httpreverseproxy_with_plugins.yml

    # Http reverse proxy plugin tasks
    - tests/cider-ci/jobs/proxy_plugins.yml

    # Style cop tasks
    - tests/cider-ci/jobs/stylecop.yml

    # Build new version 
    - tests/cider-ci/jobs/build_version.yml


                                